### ISSUE TITLE
I have to pose out another problem that i have solved.

### ISSUE THREAD

**Issue by jien2017** [ekussberg/simple-credits#9]
it is okay if your users havent enough credits to buy things ,it would notice that not enough credits,but if your users have enough credits and bought successfully,there wont be any notice and the screen stop working,where ever you click .the problem is in the woocommerceCredit.js ,you have to change " if(response.length>0)" to " if(response.length>=0)".and you have to add a var to show what you want to show to your users after they bought successfully.if any body have the same problem ,just do it.other hand,i am not a programmer and my english bad,i just want to share this to the people who have same problem with me.

**Comment by ekussberg** [comment]
@jien2017 thanks for the comment. You can edit the code here and do pull request 👍
